## 기초4_문제

In [1]:
import pandas as pd
import numpy as np

In [2]:
'''
seaborn의 타이타닉 데이터를 불러오자
'''
import seaborn as sns
df = sns.load_dataset('titanic')

In [3]:
'''
실습을 위에 데이터 소실 만들기
변경 없이 실행 시켜주시면 됩니다.
'''
df.loc[1, 'pclass'] = '?'

In [4]:
'''
데이터구조 확인 (기계적으로 확인하자)
'''
df.head()

# df.describe() # 산술데이터(평균, 표준편차, max, min, 중간값) # pclass 안나옴

survived pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0      3    male  22.0      1      0   7.2500        S  Third   
1         1      ?  female  38.0      1      0  71.2833        C  First   
2         1      3  female  26.0      0      0   7.9250        S  Third   
3         1      1  female  35.0      1      0  53.1000        S  First   
4         0      3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [5]:
'''
pclass 열의 자료형 확인 _문자열(object)
df['열'].unique() 활용
'''
df['pclass'].unique()
# print(df['pclass'].dtypes)

array([3, '?', 1, 2], dtype=object)

In [6]:
'''
pclass의 목록 확인
'''
df['pclass'].value_counts()

3    491
1    215
2    184
?      1
Name: pclass, dtype: int64

In [7]:
'''
pclass열의 누락 데이터('?') 삭제 후에 문자열을 정수형으로 변경
'''
df['pclass'].replace('?', np.nan, inplace=True)
df.dropna(subset=['pclass'], inplace=True)
df['pclass'] = df['pclass'].astype('int')

In [8]:
'''
pclass 열의 자료형 확인 _int
'''
df['pclass'].dtypes

dtype('int32')

In [9]:
'''
df['열'].unique() 를 활용하여
pclass 열의 고유값 확인
'''
print(df['pclass'].unique())

[3 1 2]


In [10]:
'''
정수형 데이터를 문자형 데이터로 변환 
1을 1등급으로 변경
2를 2등급으로 변경
3을 3등급으로 변경
'''
# ***

df['pclass'].replace({1 : '1등급', 2 : '2등급', 3 : '3등급'}, inplace=True)
df['pclass'].unique()

array(['3등급', '1등급', '2등급'], dtype=object)

In [11]:
'''
pclass 열의 자료형 확인 _object
'''
print(df['pclass'].dtypes)

object


 *범주형 데이터 처리* !!
 - Binning : cut

In [12]:
'''
origin 열의 문자열 자료형을 범주형으로 변환
'''
df['pclass'] = df['pclass'].astype('category')
# 눈으로는 안보이지만 컴퓨터는 범주형으로 인식

In [13]:
print(df['pclass'].dtypes)

category


In [14]:
'''
origin 열의 범주형을 문자열로 다시 변환
'''
df['pclass'] = df['pclass'].astype('str')
print(df['pclass'].dtypes)

object


In [15]:
'''
fare열을 np.histogram 함수로 3개의 bin으로 나누는 경계 값의 리스트 구하기
'''
# df['fare'] = df['fare'].astype('float')

cnt, bin_d = np.histogram(df['fare'], bins=3)
print(cnt)
print(bin_d)

[870  17   3]
[  0.     170.7764 341.5528 512.3292]


In [16]:
'''
위에서 구한 세가지의 그룹을 ['하', '중', '상']로 변경해 보자
'''
bin_names = ['하', '중', '상']

df['fare_bin'] = pd.cut(x = df['fare'],
                    bins = bin_d,
                    labels = bin_names,
                    include_lowest=True)

In [17]:
'''위의 변경값 확인'''
df[['fare', 'fare_bin']].tail(5)

fare fare_bin
886  13.00        하
887  30.00        하
888  23.45        하
889  30.00        하
890   7.75        하

In [18]:
'''
fare_bin 열의 범주형 데이터를 더미 변수로 변환
'''
fare_dummies = pd.get_dummies(df['fare_bin'])
print(fare_dummies.head(15))
# fare_dummies[20:40]

    하  중  상
0   1  0  0
2   1  0  0
3   1  0  0
4   1  0  0
5   1  0  0
6   1  0  0
7   1  0  0
8   1  0  0
9   1  0  0
10  1  0  0
11  1  0  0
12  1  0  0
13  1  0  0
14  1  0  0
15  1  0  0


In [ ]:
# 희소행렬?